apiVersion: apps/v1
kind: Deployment
metadata:
  name: cheese
  labels:
    app: cheese
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: cheese
  template:
    metadata:
      labels:
        app: cheese
        tier: cheese
    spec:
      containers:
      - name: cheese
        image: haeun161/cheese:latest
        envFrom:
        - secretRef:
            name: cheese-secrets
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: cheese
---
apiVersion: v1
kind: Service
metadata:
  name: cheese
  labels:
    app: cheese
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: cheese
    tier: cheese
  type: LoadBalancer
---
apiVersion: v1
kind: Secret
metadata:
  name: cheese-secrets
data:
  DB_HOST: MzQuNjQuMTczLjE4OQ== #MzQuMjIuODMuNjY= 
  DB_USER: Y2hlZXNl
  DB_PW: Y2hlZXNlMTIzNCE=
  DB_PORT: MzMwNg==
  DB_NAME: Y2hlZXNlX2Ri
  SENS_SERVICE_ID: bmNwOnNtczprcjozMDYxNzUyNTE4NjA6Y2hlZXNl
  SENS_SECRET_KEY: WE1Vb2hVZHpMbGVKeDEwR1QwRkFiSFY0b01FY2ZvMzBiU2RWSVBBWQ==
  SENS_ACCESS_KEY: YXZIU3VIa21ya1FEYVNsZDNHVE9GAFBTbGRuM0dVQg==
  SENS_MYPHONENUM: MDEwNjMwMDc3NTM=
  jwtsecret: Y2hlZXNlX2p3dF9zZWNyZXRfa2V5XzEyMzQ1Njc4OSE=
  OPENAI_API_KEY: c2stSlFQWnBqaFUwYjlaQlI1TUFhWTdUM0JsYmtGSlJ5azR3ckFlRUpLVk9nMUhoaGpG
