apiVersion: apps/v1
kind: Deployment
metadata:
  name: cheese
  labels:
    app: cheese
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: cheese
  template:
    metadata:
      labels:
        app: cheese
        tier: cheese
    spec:
      containers:
      - name: cheese
        image: haeun161/cheese:latest
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: cheese-secrets
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: cheese-secrets
              key: DB_USER
        - name: DB_PW
          valueFrom:
            secretKeyRef:
              name: cheese-secrets
              key: DB_PW
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: cheese-secrets
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: cheese-secrets
              key: DB_NAME
        - name: SENS_SERVICE_ID
          valueFrom:
            secretKeyRef:
              name: cheese-secrets
              key: SENS_SERVICE_ID
        - name: SENS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: cheese-secrets
              key: SENS_SECRET_KEY
        - name: SENS_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: cheese-secrets
              key: SENS_ACCESS_KEY
        - name: SENS_MYPHONENUM
          valueFrom:
            secretKeyRef:
              name: cheese-secrets
              key: SENS_MYPHONENUM
        - name: jwtsecret
          valueFrom:
            secretKeyRef:
              name: cheese-secrets
              key: jwtsecret
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: cheese-secrets
              key:  OPENAI_API_KEY


        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: cheese
---
apiVersion: v1
kind: Service
metadata:
  name: cheese
  labels:
    app: cheese
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: cheese
    tier: cheese
  type: LoadBalancer
---
apiVersion: v1
kind: Secret
metadata:
  name: cheese-secrets
data:
  DB_HOST: MzQuNjQuMTczLjE4OQ== #MzQuMjIuODMuNjY= 
  DB_USER: Y2hlZXNl
  DB_PW: Y2hlZXNlMTIzNCE=
  DB_PORT: MzMwNg==
  DB_NAME: Y2hlZXNlX2Ri
  SENS_SERVICE_ID: bmNwOnNtczprcjozMDYxNzUyNTE4NjA6Y2hlZXNl
  SENS_SECRET_KEY: WE1Vb2hVZHpMbGVKeDEwR1QwRkFiSFY0b01FY2ZvMzBiU2RWSVBBWQ==
  SENS_ACCESS_KEY: YXZIU3VIa21ya1FEYVNsZDNHVE9GAFBTbGRuM0dVQg==
  SENS_MYPHONENUM: MDEwNjMwMDc3NTM=
  jwtsecret: Y2hlZXNlX2p3dF9zZWNyZXRfa2V5XzEyMzQ1Njc4OSE=
  OPENAI_API_KEY: c2stSlFQWnBqaFUwYjlaQlI1TUFhWTdUM0JsYmtGSlJ5azR3ckFlRUpLVk9nMUhoaGpG
