apiVersion: apps/v1
kind: Deployment
metadata:
  name: cheese
  labels:
    app: cheese
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: cheese
  template:
    metadata:
      labels:
        app: cheese
        tier: cheese
    spec:
      containers:
      - name: cheese
        image: minju0907/cheese:latest
        # env:
        # - configMapRef:
        #     name: jwtsecret
        # - secretRef:
        #     name: jwtsecret
        env:
        - name: CONFIGMAP_ENV_VAR_NAME
          valueFrom:
            configMapKeyRef:
              name: jwtsecret
              key: key-in-configmap
        - name: SECRET_ENV_VAR_NAME
          valueFrom:
            secretKeyRef:
              name: jwtsecret
              key: key-in-secret
        envFrom:
        - secretRef:
            name: jwt-secret
            key: jwtsecret
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: cheese
---
apiVersion: v1
kind: Service
metadata:
  name: cheese
  labels:
    app: cheese
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: cheese
    tier: cheese
  type: LoadBalancer
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
stringData:
  jwtsecret : cheese_jwt_secret_key_123456789!
