apiVersion: apps/v1
kind: Deployment
metadata:
  name: cheese
  labels:
    app: cheese
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: cheese
  template:
    metadata:
      labels:
        app: cheese
        tier: cheese
    spec:
      containers:
      - name: cheese
        image: haeun161/cheese:latest
        envFrom:
        - secretRef:
            name: cheese-secrets
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: cheese
