apiVersion: apps/v1
kind: Deployment
metadata:
  name: cheese
  labels:
    app: cheese
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: cheese
  template:
    metadata:
      labels:
        app: cheese
        tier: cheese
    spec:
      containers:
      - name: cheese
        image: haeun161/cheese:latest
        env:
        - name: jwtsecret # 환경 변수의 이름
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: jwtsecret
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: cheese
---
apiVersion: v1
kind: Service
metadata:
  name: cheese
  labels:
    app: cheese
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: cheese
    tier: cheese
  type: LoadBalancer
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
data: #key:value로 지정
  jwtsecret : Y2hlZXNlX2p3dF9zZWNyZXRfa2V5XzEyMzQ1Njc4OSE=
