apiVersion: v1
kind: Secret
metadata:
  name: cheese-secrets
data:
  DB_HOST: MzQuNjQuMTczLjE4OQ==
  DB_USER: Y2hlZXNl
  DB_PW: Y2hlZXNlMTIzNCE=
  DB_PORT: MzMwNg==
  DB_NAME: Y2hlZXNlX2Ri
  SENS_SERVICE_ID: bmNwOnNtczprcjozMDYxNzUyNTE4NjA6Y2hlZXNl
  SENS_SECRET_KEY: WE1Vb2hVZHpMbGVKeDEwR1QwRkFiSFY0b01FY2ZvMzBiU2RWSVBBWQ==
  SENS_MYPHONENUM: MDEwNjMwMDc3NTM=
  jwtsecret: Y2hlZXNlX2p3dF9zZWNyZXRfa2V5XzEyMzQ1Njc4OSE=
  OPENAI_API_KEY: c2stSlFQWnBqaFUwYjlaQlI1TUFhWTdUM0JsYmtGSlJ5azR3ckFlRUpLVk9nMUhoaGpG
  SENS_ACCESS_KEY: YXZIU3VIa21ya1FEYVNsZDNHVUI=
